name: instagram_private_api
description: A starting point for Dart libraries or applications.
# version: 1.0.0

environment:
  sdk: '>=2.2.2 <3.0.0'


dependencies:
  uuid: ^2.0.1
  json_annotation: ^3.0.0
  cookie_jar: 
  dio: ^3.0.10
  dio_cookie_manager:
  crypto: ^2.1.0
  hex: ^0.1.2
  image: ^2.1.4
  intl: ^0.16.1
  meta: ^1.1.7

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
